#!/usr/bin/env python3
from render_common import *

lines = []
lines.append(prompt("~", "tux2lab deploy"))
BAR = "═"*67
DASH = "-"*62
lines.append(whole(BAR, GREEN))
lines.append(whole("  tux2lab — Lab Infrastructure Deployment", GREEN))
lines.append(whole(BAR, GREEN))
lines.append(whole("[INFO] Running pre-flight checks...", MAGENTA))
lines.append(whole("[INFO] Pre-flight checks passed.", MAGENTA))
lines.append(task("Capturing network configuration from labbr0...", "[DONE]", GREEN))
lines.append(kv("  ✓ Bridge           :", "labbr0"))
lines.append(kv("  ✓ IPv4 Address     :", "10.28.28.1"))
lines.append(kv("  ✓ IPv4 Network     :", "10.28.28.0/22"))
lines.append(kv("  ✓ IPv4 Broadcast   :", "10.28.31.255"))
lines.append(kv("  ✓ DHCPv4 Pool      :", "10.28.31.156 - 10.28.31.254"))
lines.append(kv("  ✓ IPv6 Address     :", "fd28:2808:2020:3000::1"))
lines.append(kv("  ✓ IPv6 Network     :", "fd28:2808:2020:3000::/64"))
lines.append(kv("  ✓ DHCPv6 Pool      :", "fd28:2808:2020:3000::3ff - fd28:2808:2020:3000::461"))
lines.append(kv("  ✓ Lab Infra Server :", "tux2lab-engine.musubram.internal"))
lines.append(kv("  ✓ Admin User       :", "musubram"))
lines.append(whole("The following will be configured:", YELLOW))
lines.append(whole("  - Generate SSH keypair for lab access", YELLOW))
lines.append(whole("  - Generate self-signed SSL certificate", YELLOW))
lines.append(whole("  - Generate service configurations (DNS, DHCP, NTP, HTTP, TFTP, NFS)", YELLOW))
lines.append(whole("  - Pull and start tux2lab-engine container (DNS, DHCP, NTP, HTTP, TFTP)", YELLOW))
lines.append(whole("  - Start NFS server on host (bound to lab bridge)", YELLOW))
lines.append(whole("  - Configure host DNS resolution and SSH", YELLOW))
lines.append(whole("Are you sure you want to continue? (yes/no): yes", DEFAULT))
lines.append(whole("Enter your Lab Infra Global password:", DEFAULT))
lines.append(whole("Re-enter Lab Infra Global password:", DEFAULT))
lines.append(whole("[INFO] Credentials ready for user 'musubram'.", MAGENTA))
lines.append(task("Generating SSH keypair...", "[DONE]", GREEN))
lines.append(whole("[INFO] SSH keys generated at /tux2lab-data/lab-config/ssh-keys/", MAGENTA))
lines.append(task("Generating SSL certificate...", "[DONE]", GREEN))
lines.append(whole("[INFO] SSL certificate generated and trusted by host.", MAGENTA))
lines.append(task("Generating lab_environment.json...", "[DONE]", GREEN))
lines.append(whole("[INFO] Lab environment written to /tux2lab-data/lab-config/lab_environment.json", MAGENTA))
lines.append(task("Generating compatibility lab_environment_vars...", "[DONE]", GREEN))
lines.append(whole("[INFO] Generating service configurations...", MAGENTA))
lines.append(whole("[INFO] Generating service configs from /tux2lab-data/lab-config/lab_environment.json...", MAGENTA))
lines.append(task("Generating nginx config...", "[DONE]", GREEN))
lines.append(task("Generating kea-dhcp4 config...", "[DONE]", GREEN))
lines.append(task("Generating kea-dhcp6 config...", "[DONE]", GREEN))
lines.append(task("Generating kea-ctrl-agent config...", "[DONE]", GREEN))
lines.append(task("Generating radvd config...", "[DONE]", GREEN))
lines.append(task("Generating chrony config...", "[DONE]", GREEN))
lines.append(task("Generating NFS exports...", "[DONE]", GREEN))
lines.append(task("Setting up tftpboot directory...", "[DONE]", GREEN))
lines.append(task("Setting up named directories...", "[DONE]", GREEN))
lines.append(whole("[SUCCESS] All service configurations generated.", GREEN))
lines.append(whole("[INFO] Setting up DNS with dnsbinder...", MAGENTA))
lines.append(task("Fetching network information from the system...", "[DONE]", GREEN))
lines.append(task("Configuring named.conf from template...", "[DONE]", GREEN))
lines.append(task("Installing root hints file (named.root)...", "[DONE]", GREEN))
lines.append(task("Adding DNS zones to named.conf...", "[DONE]", GREEN))
lines.append(task("Creating and configuring zone files...", "[DONE]", GREEN))
lines.append(whole('[SUCCESS] DNS domain "musubram.internal" configured successfully.', GREEN))
lines.append(whole("  Server : tux2lab-engine.musubram.internal", GREEN))
lines.append(whole("  IPv4   : 10.28.28.1", GREEN))
lines.append(whole("  IPv6   : fd28:2808:2020:3000::1", GREEN))
lines.append(task("Waiting for labbr0 to be UP...", "[DONE]", GREEN))
lines.append(task("Waiting for IPv6 DAD to complete...", "[DONE]", GREEN))
lines.append(task("Opening firewall for labbr0...", "[SKIP]", YELLOW))
lines.append(task("Pulling tux2lab-engine container image (0m 6s)...", "[DONE]", GREEN))
lines.append(task("Starting tux2lab-engine container (0m 2s)...", "[DONE]", GREEN))
lines.append(whole("[INFO] Container 'tux2lab-engine' is running.", MAGENTA))
lines.append(task("Creating IPv4 DNS records for DHCPv4 pool...", "[DONE]", GREEN))
lines.append(task("Creating IPv6 DNS records for DHCPv6 pool...", "[DONE]", GREEN))
lines.append(task("Starting NFS server on host...", "[DONE]", GREEN))
lines.append(task("Configuring DNS resolution on host...", "[DONE]", GREEN))
lines.append(task("Configuring SSH for lab domain...", "[DONE]", GREEN))
lines.append(whole("[INFO] Running health check...", MAGENTA))
lines.append(whole(DASH, CYAN))
lines.append(whole("tux2lab Health Check", CYAN))
lines.append(whole("Lab Infra Server     : tux2lab-engine.musubram.internal", CYAN))
lines.append(whole("IPv4 Address         : 10.28.28.1", CYAN))
lines.append(whole("IPv6 Address         : fd28:2808:2020:3000::1", CYAN))
lines.append(whole("Container            : tux2lab-engine", CYAN))
lines.append(whole(DASH, CYAN))
lines.append(whole("Deep Validation of Services:", CYAN))
lines.append(whole(DASH, CYAN))
lines.append(passline("DNS forward lookup (tux2lab-engine.musubram.internal → 10.28.28.1)"))
lines.append(passline("DNS reverse lookup (10.28.28.1 → tux2lab-engine.musubram.internal)"))
lines.append(passline("Kea DHCPv4 process running"))
lines.append(passline("Kea DHCPv6 process running"))
lines.append(passline("Chronyd process running"))
lines.append(passline("NTP synchronized (chrony leap status normal)"))
lines.append(passline("TFTP boot file exists (/tux2lab-data/tftpboot/ipxe.efi)"))
lines.append(passline("NFS export available (/tux2lab-data)"))
lines.append(passline("Firewall allows traffic on labbr0"))
lines.append(passline("Nginx HTTP response (200 OK)"))
lines.append(passline("Nginx HTTPS response (200 OK)"))
lines.append(whole(DASH, CYAN))
lines.append(whole("Port Reachability (dual-stack):", CYAN))
lines.append(whole(DASH, CYAN))
lines.append(portline("DNS Server"))
lines.append(portline("DHCP Server"))
lines.append(portline("NTP Server"))
lines.append(portline("TFTP Server"))
lines.append(portline("NFS Server"))
lines.append(portline("Web Server"))
lines.append(whole(DASH, CYAN))
lines.append(whole("Health Check Summary of tux2lab:", CYAN))
lines.append(whole("Deep Validation   : 11/11 checks passed", CYAN))
lines.append(whole("Port Reachability : 6/6 services fully reachable (dual-stack)", CYAN))
lines.append(whole(DASH, CYAN))
lines.append(whole("[SUCCESS] tux2lab health is STABLE.", GREEN))
lines.append(whole(DASH, CYAN))
lines.append(whole(BAR, GREEN))
lines.append(whole("  tux2lab Lab Infrastructure deployed successfully!", GREEN))
lines.append(whole(BAR, GREEN))
lines.append(prompt("~", ""))

render(lines, "tux2lab-deploy.png")
