#!/usr/bin/env python3
from render_common import *

lines = []
lines.append(prompt("~", "tux2lab vm install -H testvm1 -d almalinux -v 10"))
lines.append(task('Generating MAC address for VM "testvm1.musubram.internal"...', "[DONE]", GREEN))
lines.append(whole("[INFO] Creating first boot environment for 'testvm1.musubram.internal' using ksmanager...", MAGENTA))
lines.append(whole("[INFO] OS distribution selected via --distro flag: almalinux", MAGENTA))
lines.append(whole("[INFO] OS distribution selected: almalinux 10", MAGENTA))
lines.append(whole('[INFO] Checking DNS record for "testvm1.musubram.internal"...', MAGENTA))
lines.append(whole('[INFO] No DNS record found for "testvm1.musubram.internal".', MAGENTA))
lines.append(task("Creating host record testvm1.musubram.internal...", "[DONE]", GREEN))
lines.append(task("Updating serial numbers of zone files...", "[DONE]", GREEN))
lines.append(task("Reloading DNS...", "[DONE]", GREEN))
lines.append(task("Validating forward look up...", "[DONE]", GREEN))
lines.append(task("Validating reverse look up...", "[DONE]", GREEN))
lines.append(whole("[INFO] FYI : testvm1.musubram.internal", MAGENTA))
lines.append(whole("             ├── IPv4: 10.28.28.2", MAGENTA))
lines.append(whole("             ├── IPv6: fd28:2808:2020:3000::2", MAGENTA))
lines.append(whole("             └── TTL : 3600 (default) seconds", MAGENTA))
lines.append(whole("[SUCCESS] Created host record testvm1.musubram.internal", GREEN))
lines.append(task("Flushing DNS cache...", "[DONE]", GREEN))
lines.append(whole("[INFO] Using MAC address provided via --mac flag: 52:54:00:16:b8:a8", MAGENTA))
lines.append(task("Caching MAC address...", "[DONE]", GREEN))
lines.append(task("Generating golden boot network config...", "[DONE]", GREEN))
lines.append(task("Setting environment variables in network config...", "[DONE]", GREEN))
lines.append(task("Finalizing configuration files...", "[DONE]", GREEN))
lines.append(task("Updating KEA DHCP reservations...", "[DONE]", GREEN))
lines.append(whole("Configuration Summary:", DEFAULT))
lines.append(kv("  ✓ Hostname         :", "testvm1.musubram.internal"))
lines.append(kv("  ✓ MAC Address      :", "52:54:00:16:b8:a8"))
lines.append(kv("  ✓ Stack Mode       :", "dual"))
lines.append(kv("  ✓ IPv4 Address     :", "10.28.28.2"))
lines.append(kv("  ✓ IPv4 Gateway     :", "10.28.28.1"))
lines.append(kv("  ✓ IPv4 Network     :", "10.28.28.0/22"))
lines.append(kv("  ✓ IPv4 DNS         :", "10.28.28.1"))
lines.append(kv("  ✓ IPv6 Address     :", "fd28:2808:2020:3000::2"))
lines.append(kv("  ✓ IPv6 Gateway     :", "fd28:2808:2020:3000::1"))
lines.append(kv("  ✓ IPv6 Network     :", "fd28:2808:2020:3000::/64"))
lines.append(kv("  ✓ IPv6 DNS         :", "fd28:2808:2020:3000::1"))
lines.append(kv("  ✓ Domain           :", "musubram.internal"))
lines.append(kv("  ✓ Lab Infra Server :", "tux2lab-engine.musubram.internal"))
lines.append(kv("  ✓ Requested OS     :", "AlmaLinux 10"))
lines.append(task("Updating provisioning registry...", "[DONE]", GREEN))
lines.append(whole("[INFO] Golden boot configs ready for 'testvm1.musubram.internal'.", MAGENTA))
lines.append(task("Updating /etc/hosts for testvm1.musubram.internal...", "[DONE]", GREEN))
lines.append(task("Cloning golden image disk for 'testvm1.musubram.internal'...", "[DONE]", GREEN))
lines.append(whole('[INFO] Starting VM installation of "testvm1.musubram.internal" via golden image disk...', MAGENTA))
lines.append(whole("[INFO] VM specs: 2 vCPUs, 2 GiB RAM, 30 GiB disk", MAGENTA))
lines.append(whole('[SUCCESS] VM "testvm1.musubram.internal" installation via golden image disk initiated successfully.', GREEN))
lines.append(whole("    ▸ Installation via golden image disk takes ~1 minute per VM.", YELLOW))
lines.append(whole("    ▸ To monitor progress: tux2lab vm console -H testvm1.musubram.internal", YELLOW))
lines.append(whole("    ▸ To check VM status:  tux2lab vm list", YELLOW))
lines.append(prompt("~", ""))

render(lines, "tux2lab-vm-install.png")
