#!/usr/bin/env python3
from render_common import *

def vm_block(lines, num, name, mac, ipv4, ipv6):
    fqdn = f"{name}.musubram.internal"
    lines.append(whole(f"[INFO] Processing VM {num}/3: {fqdn}", MAGENTA))
    lines.append(task(f'Generating MAC address for VM "{fqdn}"...', "[DONE]", GREEN))
    lines.append(whole(f"[INFO] Creating first boot environment for '{fqdn}' using ksmanager...", MAGENTA))
    lines.append(whole("[INFO] OS distribution selected via --distro flag: almalinux", MAGENTA))
    lines.append(whole("[INFO] OS distribution selected: almalinux 10", MAGENTA))
    lines.append(whole(f'[INFO] Checking DNS record for "{fqdn}"...', MAGENTA))
    lines.append(whole(f'[INFO] No DNS record found for "{fqdn}".', MAGENTA))
    lines.append(task(f"Creating host record {fqdn}...", "[DONE]", GREEN))
    lines.append(task("Updating serial numbers of zone files...", "[DONE]", GREEN))
    lines.append(task("Reloading DNS...", "[DONE]", GREEN))
    lines.append(task("Validating forward look up...", "[DONE]", GREEN))
    lines.append(task("Validating reverse look up...", "[DONE]", GREEN))
    lines.append(whole(f"[INFO] FYI : {fqdn}", MAGENTA))
    lines.append(whole(f"             ├── IPv4: {ipv4}", MAGENTA))
    lines.append(whole(f"             ├── IPv6: {ipv6}", MAGENTA))
    lines.append(whole("             └── TTL : 3600 (default) seconds", MAGENTA))
    lines.append(whole(f"[SUCCESS] Created host record {fqdn}", GREEN))
    lines.append(task("Flushing DNS cache...", "[DONE]", GREEN))
    lines.append(whole(f"[INFO] Using MAC address provided via --mac flag: {mac}", MAGENTA))
    lines.append(task("Caching MAC address...", "[DONE]", GREEN))
    lines.append(task("Generating golden boot network config...", "[DONE]", GREEN))
    lines.append(task("Setting environment variables in network config...", "[DONE]", GREEN))
    lines.append(task("Finalizing configuration files...", "[DONE]", GREEN))
    lines.append(task("Updating KEA DHCP reservations...", "[DONE]", GREEN))
    lines.append(whole("Configuration Summary:", DEFAULT))
    lines.append(kv("  ✓ Hostname         :", fqdn))
    lines.append(kv("  ✓ MAC Address      :", mac))
    lines.append(kv("  ✓ Stack Mode       :", "dual"))
    lines.append(kv("  ✓ IPv4 Address     :", ipv4))
    lines.append(kv("  ✓ IPv4 Gateway     :", "10.28.28.1"))
    lines.append(kv("  ✓ IPv4 Network     :", "10.28.28.0/22"))
    lines.append(kv("  ✓ IPv4 DNS         :", "10.28.28.1"))
    lines.append(kv("  ✓ IPv6 Address     :", ipv6))
    lines.append(kv("  ✓ IPv6 Gateway     :", "fd28:2808:2020:3000::1"))
    lines.append(kv("  ✓ IPv6 Network     :", "fd28:2808:2020:3000::/64"))
    lines.append(kv("  ✓ IPv6 DNS         :", "fd28:2808:2020:3000::1"))
    lines.append(kv("  ✓ Domain           :", "musubram.internal"))
    lines.append(kv("  ✓ Lab Infra Server :", "tux2lab-engine.musubram.internal"))
    lines.append(kv("  ✓ Requested OS     :", "AlmaLinux 10"))
    lines.append(task("Updating provisioning registry...", "[DONE]", GREEN))
    lines.append(whole(f"[INFO] Golden boot configs ready for '{fqdn}'.", MAGENTA))
    lines.append(task(f"Updating /etc/hosts for {fqdn}...", "[DONE]", GREEN))
    lines.append(task(f"Cloning golden image disk for '{fqdn}'...", "[DONE]", GREEN))
    lines.append(whole(f'[INFO] Starting VM installation of "{fqdn}" via golden image disk...', MAGENTA))
    lines.append(whole("[INFO] VM specs: 2 vCPUs, 2 GiB RAM, 30 GiB disk", MAGENTA))

lines = []
lines.append(prompt("~", "tux2lab vm install -H testvm2,testvm3,testvm4 -d almalinux -v 10"))
vm_block(lines, 1, "testvm2", "52:54:00:52:cd:2e", "10.28.28.3", "fd28:2808:2020:3000::3")
vm_block(lines, 2, "testvm3", "52:54:00:e5:3b:1c", "10.28.28.4", "fd28:2808:2020:3000::4")
vm_block(lines, 3, "testvm4", "52:54:00:0f:9d:b2", "10.28.28.5", "fd28:2808:2020:3000::5")
lines.append(whole("[SUMMARY] Results: installation via golden image disk", WHITE))
lines.append(whole("  DONE: 3/3", GREEN))
lines.append(whole("    - testvm2.musubram.internal", GREEN))
lines.append(whole("    - testvm3.musubram.internal", GREEN))
lines.append(whole("    - testvm4.musubram.internal", GREEN))
lines.append(whole("[INFO] Installation via golden image disk takes ~1 minute per VM.", MAGENTA))
lines.append(whole("[INFO] To monitor progress: tux2lab vm console -H <hostname>", MAGENTA))
lines.append(whole("[INFO] To check VM status: tux2lab vm list", MAGENTA))
lines.append(prompt("~", ""))

render(lines, "tux2lab-vm-install-multi.png")
