#!/usr/bin/env python3
from render_common import *

HBAR = "━"*70
lines = []
lines.append(prompt("~", "tux2lab golden-image build almalinux -v 10"))
lines.append(task("Checking internet connectivity...", "[DONE]", GREEN))
lines.append(task("Generating MAC address for golden image VM...", "[DONE]", GREEN))
lines.append(whole("[INFO] Creating PXE environment for golden image...", MAGENTA))
lines.append(whole("[INFO] OS distribution selected via --distro flag: almalinux", MAGENTA))
lines.append(whole("[INFO] OS distribution selected: almalinux 10", MAGENTA))
lines.append(whole('[INFO] Checking DNS record for "almalinux-10-golden-image.musubram.internal"...', MAGENTA))
lines.append(whole('[INFO] No DNS record found for "almalinux-10-golden-image.musubram.internal".', MAGENTA))
lines.append(task("Creating host record almalinux-10-golden-image.musubram.internal...", "[DONE]", GREEN))
lines.append(task("Updating serial numbers of zone files...", "[DONE]", GREEN))
lines.append(task("Reloading DNS...", "[DONE]", GREEN))
lines.append(task("Validating forward look up...", "[DONE]", GREEN))
lines.append(task("Validating reverse look up...", "[DONE]", GREEN))
lines.append(whole("[INFO] FYI : almalinux-10-golden-image.musubram.internal", MAGENTA))
lines.append(whole("             ├── IPv4: 10.28.28.2", MAGENTA))
lines.append(whole("             ├── IPv6: fd28:2808:2020:3000::2", MAGENTA))
lines.append(whole("             └── TTL : 3600 (default) seconds", MAGENTA))
lines.append(whole("[SUCCESS] Created host record almalinux-10-golden-image.musubram.internal", GREEN))
lines.append(task("Flushing DNS cache...", "[DONE]", GREEN))
lines.append(whole("[INFO] Using MAC address provided via --mac flag: 52:54:00:7a:65:99", MAGENTA))
lines.append(task("Caching MAC address...", "[DONE]", GREEN))
lines.append(task("Generating kickstart profile and iPXE configs...", "[DONE]", GREEN))
lines.append(task("Finalizing configuration files...", "[DONE]", GREEN))
lines.append(task("Updating KEA DHCP reservations...", "[DONE]", GREEN))
lines.append(whole("Configuration Summary:", DEFAULT))
lines.append(kv("  ✓ Hostname         :", "almalinux-10-golden-image.musubram.internal"))
lines.append(kv("  ✓ MAC Address      :", "52:54:00:7a:65:99"))
lines.append(kv("  ✓ Stack Mode       :", "dual"))
lines.append(kv("  ✓ IPv4 Address     :", "10.28.28.2"))
lines.append(kv("  ✓ IPv4 Gateway     :", "10.28.28.1"))
lines.append(kv("  ✓ IPv4 Network     :", "10.28.28.0/22"))
lines.append(kv("  ✓ IPv4 DNS         :", "10.28.28.1"))
lines.append(kv("  ✓ IPv6 Address     :", "fd28:2808:2020:3000::2"))
lines.append(kv("  ✓ IPv6 Gateway     :", "fd28:2808:2020:3000::1"))
lines.append(kv("  ✓ IPv6 Network     :", "fd28:2808:2020:3000::/64"))
lines.append(kv("  ✓ IPv6 DNS         :", "fd28:2808:2020:3000::1"))
lines.append(kv("  ✓ Domain           :", "musubram.internal"))
lines.append(kv("  ✓ Lab Infra Server :", "tux2lab-engine.musubram.internal"))
lines.append(kv("  ✓ Requested OS     :", "AlmaLinux 10"))
lines.append(task("Updating provisioning registry...", "[DONE]", GREEN))
lines.append(whole("[INFO] Kickstart configs ready for 'almalinux-10-golden-image.musubram.internal'.", MAGENTA))
lines.append(whole('[INFO] Starting installation of VM "almalinux-10-golden-image.musubram.internal" to create golden image disk...', MAGENTA))
lines.append(whole(HBAR, CYAN))
lines.append(whole("Preparing Golden Image with OS Installation via PXE Network Boot", CYAN))
lines.append(whole(HBAR, CYAN))
lines.append(whole("  To monitor: tux2lab vm console -H almalinux-10-golden-image.musubram.internal", YELLOW))
lines.append(whole("  This may take several minutes depending on the distribution and internet speed.", YELLOW))
lines.append(whole("  ✓ Golden image preparation completed (6m 9s)", GREEN))
lines.append(task("Cleaning up provisioning environment...", "[DONE]", GREEN))
lines.append(task("Cleaning up temporary VM...", "[DONE]", GREEN))
lines.append(whole("[SUCCESS] Golden image created successfully for almalinux 10", GREEN))
lines.append(prompt("~", ""))

render(lines, "tux2lab-golden-build.png")
