#!/usr/bin/env python3
from render_common import *

DASH = "-"*62
lines = []
lines.append(prompt("~", "tux2lab health"))
lines.append(whole(DASH, CYAN))
lines.append(whole("tux2lab Health Check", CYAN))
lines.append(whole("Lab Infra Server     : tux2lab-engine.musubram.internal", CYAN))
lines.append(whole("IPv4 Address         : 10.28.28.1", CYAN))
lines.append(whole("IPv6 Address         : fd28:2808:2020:3000::1", CYAN))
lines.append(whole("Container            : tux2lab-engine", CYAN))
lines.append(whole(DASH, CYAN))
lines.append(whole("Deep Validation of Services:", CYAN))
lines.append(whole(DASH, CYAN))
lines.append(passline("DNS forward lookup (tux2lab-engine.musubram.internal → 10.28.28.1)"))
lines.append(passline("DNS reverse lookup (10.28.28.1 → tux2lab-engine.musubram.internal)"))
lines.append(passline("Kea DHCPv4 process running"))
lines.append(passline("Kea DHCPv6 process running"))
lines.append(passline("Chronyd process running"))
lines.append(passline("NTP synchronized (chrony leap status normal)"))
lines.append(passline("TFTP boot file exists (/tux2lab-data/tftpboot/ipxe.efi)"))
lines.append(passline("NFS export available (/tux2lab-data)"))
lines.append(passline("Firewall allows traffic on labbr0"))
lines.append(passline("Nginx HTTP response (200 OK)"))
lines.append(passline("Nginx HTTPS response (200 OK)"))
lines.append(whole(DASH, CYAN))
lines.append(whole("Port Reachability (dual-stack):", CYAN))
lines.append(whole(DASH, CYAN))
lines.append(portline("DNS Server"))
lines.append(portline("DHCP Server"))
lines.append(portline("NTP Server"))
lines.append(portline("TFTP Server"))
lines.append(portline("NFS Server"))
lines.append(portline("Web Server"))
lines.append(whole(DASH, CYAN))
lines.append(whole("Health Check Summary of tux2lab:", CYAN))
lines.append(whole("Deep Validation   : 11/11 checks passed", CYAN))
lines.append(whole("Port Reachability : 6/6 services fully reachable (dual-stack)", CYAN))
lines.append(whole(DASH, CYAN))
lines.append(whole("[SUCCESS] tux2lab health is STABLE.", GREEN))
lines.append(whole(DASH, CYAN))
lines.append(prompt("~", ""))

render(lines, "tux2lab-health.png")
