---
# tasks file for setup_pxe_boot_of_server
- name: Configure /etc/kea/kea-dhcp4.conf
  become: true
  template:
    src: kea_dhcp4_conf.j2
    dest: /etc/kea/kea-dhcp4.conf

- name: Configure /etc/kea/kea-dhcp6.conf
  become: true
  template:
    src: kea_dhcp6_conf.j2
    dest: /etc/kea/kea-dhcp6.conf

- name: Configure /etc/kea/kea-ctrl-agent.conf
  become: true
  template:
    src: kea_ctrl_agent_conf.j2
    dest: /etc/kea/kea-ctrl-agent.conf

- name: Configure /etc/radvd.conf for IPv6 Router Advertisements
  become: true
  template:
    src: radvd_conf.j2
    dest: /etc/radvd.conf

- name: Enable IPv6 forwarding for radvd
  become: true
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/99-ipv6-forwarding.conf
    sysctl_set: true
    reload: true

- name: Create tux2lab mount point under /{{ ansible_facts.env.dnsbinder_server_short_name }}.{{ ansible_facts.env.dnsbinder_domain }}
  file:
    path: "/{{ ansible_facts.env.dnsbinder_server_short_name }}.{{ ansible_facts.env.dnsbinder_domain }}/tux2lab"
    state: directory

- name: Bind mount /tux2lab as /{{ ansible_facts.env.dnsbinder_server_short_name }}.{{ ansible_facts.env.dnsbinder_domain }} update an entry in fstab as well 
  become: true
  ansible.posix.mount:
    path: "/{{ ansible_facts.env.dnsbinder_server_short_name }}.{{ ansible_facts.env.dnsbinder_domain }}/tux2lab"
    src: "/tux2lab"
    fstype: none
    opts: "bind,ro,uid={{ ansible_facts.env.mgmt_super_user }},gid={{ ansible_facts.env.mgmt_super_user }}"
    state: mounted

- name: Create almalinux-latest mount point under /{{ ansible_facts.env.dnsbinder_server_short_name }}.{{ ansible_facts.env.dnsbinder_domain }}
  file:
    path: "/{{ ansible_facts.env.dnsbinder_server_short_name }}.{{ ansible_facts.env.dnsbinder_domain }}/almalinux-latest"
    state: directory

- name: Mount AlmaLinux ISO from CD-ROM and update an entry in fstab as well 
  become: true
  ansible.posix.mount:
    path: "/{{ ansible_facts.env.dnsbinder_server_short_name }}.{{ ansible_facts.env.dnsbinder_domain }}/almalinux-latest"
    src: "{{ ansible_facts.env.default_linux_distro_iso_path }}"
    fstype: iso9660
    opts: "uid={{ ansible_facts.env.mgmt_super_user }},gid={{ ansible_facts.env.mgmt_super_user }}"
    state: mounted

- name: Create /{{ ansible_facts.env.dnsbinder_server_short_name }}.{{ ansible_facts.env.dnsbinder_domain }}/ipxe to manage iPXE
  file:
    path: "/{{ ansible_facts.env.dnsbinder_server_short_name }}.{{ ansible_facts.env.dnsbinder_domain }}/ipxe"
    state: directory

- name: Deploy ipxe.efi for HTTP boot
  become: true
  copy:
    src: ipxe.efi
    dest: "/{{ ansible_facts.env.dnsbinder_server_short_name }}.{{ ansible_facts.env.dnsbinder_domain }}/ipxe/ipxe.efi"
    mode: '0644'

- name: Deploy ipxe.efi to TFTP directory for PXE boot
  become: true
  copy:
    src: ipxe.efi
    dest: "/var/lib/tftpboot/ipxe.efi"
    mode: '0644'

- name: Enable and Start tftp.socket
  become: true
  systemd_service:
    name: tftp.socket
    state: started
    enabled: true

- name: Enable and Start kea-dhcp4,kea-dhcp6,kea-ctrl-agent,radvd
  become: true
  systemd_service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - "kea-dhcp4"
    - "kea-dhcp6"
    - "kea-ctrl-agent"
    - "radvd"

- name: Restart kea-dhcp4,kea-dhcp6,kea-ctrl-agent,radvd
  become: true
  systemd_service:
    name: "{{ item }}"
    state: restarted
  loop:
    - "kea-dhcp4"
    - "kea-dhcp6"
    - "kea-ctrl-agent"
    - "radvd"

- name: Create command sym-link dnsbinder
  become: true
  file:
    src: /tux2lab/named-manage/dnsbinder.sh
    dest: /usr/sbin/dnsbinder
    state: link

- name: Set execute permissions on ksmanager.sh
  become: true
  file:
    path: /tux2lab/ks-manage/ksmanager.sh
    mode: '0755'

- name: Create command sym-link ksmanager
  become: true
  file:
    src: /tux2lab/ks-manage/ksmanager.sh
    dest: /usr/local/bin/ksmanager
    state: link

- name: Set execute permissions on prepare-distro-for-ksmanager.sh
  become: true
  file:
    path: /tux2lab/ks-manage/prepare-distro-for-ksmanager.sh
    mode: '0755'

- name: Create command sym-link prepare-distro-for-ksmanager
  become: true
  file:
    src: /tux2lab/ks-manage/prepare-distro-for-ksmanager.sh
    dest: /usr/local/bin/prepare-distro-for-ksmanager
    state: link

################################ EOF ##################################
